### ISSUE TITLE
Team Casimir Funk Code Review

### ISSUE THREAD

**Issue by yingyinlii** [vishalival/eep153-margaret-reid#1]
Hi, 

First off, very impressive code! All the code works perfectly on my end. The notebook is well-organized and covers all required deliverables. I also liked how you put comments and notes before code to improve readability and clarity. 

A small suggestion I have, is regarding dropping rows with df_b.dropna (how='any') without assigning it back to df_b or another variable, in solution part 2. 

This might result in the original df_b DataFrame remaining unchanged for any future operations. The operation then might not do anything in the context of the script. Maybe consider changing it to df_b.dropna(how='any', inplace=True) or df_b=df_b.dropna(how='any').

Overall, the code is very neat and good luck with the rest of your project! :))

**Comment by vishalival** [comment]
Hi,

Thank you so much for taking the time to run everything, glad it all works perfectly for you. 
Thanks for the suggestion, I totally didn't catch that and will definitely take that modification into account by including the inplace keyword.

Thank you so much again!

**Comment by vishalival** [comment]
Issue closed, code modified now
